[toolchain]
anchor_version = "0.28.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nova_insurance = "4iAKZaYASzqvW17iaZLZCxDxNTYCEJn4STL9RVdqC9V8"

[programs.devnet]
nova_insurance = "4iAKZaYASzqvW17iaZLZCxDxNTYCEJn4STL9RVdqC9V8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=78f95630-1552-44ce-928b-d936a784e95a"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
